<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h2>Start earning money today</h2>
    </div>
</div>

<?php
$this->headTitle('Sign in');

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Your E-mail address',
    'autofocus' => true
]);$this->headTitle('Sign in');

$form->get('password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Password',
    'autofocus' => true
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

?>

<?= $this->form()->openTag($form); ?>
<div class="col-md-offset-4 col-sm-12 col-md-4">
    <div class="form-group">
        <?= $this->formLabel($form->get('email')); ?>
        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('password')); ?>
        <?= $this->formElement($form->get('password')); ?>
        <?= $this->formElementErrors($form->get('password')); ?>
    </div>

    <div class="form-group">
        <?= $this->formElement($form->get('submit')); ?>
    </div>
</div>
<?= $this->form()->closeTag(); ?>


