<?php
$this->headTitle('Sign in');

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Hello Pawel, how are you?',
    'autofocus' => true
]);$this->headTitle('Sign in');

$form->get('password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Pawel, please insert your key',
    'autofocus' => true
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

?>

<?= $this->form()->openTag($form); ?>
<div class="col-sm-offset-3 col-sm-12 col-md-6">
<div class="form-group">
    <?= $this->formLabel($form->get('email')); ?>
    <?= $this->formElement($form->get('email')); ?>
    <?= $this->formElementErrors($form->get('email')); ?>
</div>

<div class="form-group">
    <?= $this->formLabel($form->get('password')); ?>
    <?= $this->formElement($form->get('password')); ?>
    <?= $this->formElementErrors($form->get('password')); ?>
</div>

<div class="form-group">
    <?= $this->formElement($form->get('submit')); ?>
</div>
</div>
<?= $this->form()->closeTag(); ?>


