<!-- Main jumbotron for a primary marketing message or call to action -->
<!--<div class="jumbotron">-->
<!--    <div class="container">-->
<!--        <h1>Blog</h1>-->
<!--    </div>-->
<!--</div>-->

    <div class="jumbotron jumbotron-pic row">
            <h1 class="text-center" style="color: #fff">Blog</h1>
        <div class="cleaner"></div>
    </div>


<div class="page-header">
    <h1 id="timeline">Einträge</h1>
</div>

<div class="container">
    <div class="row equal">
        <ul class="timeline">
            <?php $i = 1;?>
            <?php $j = 2;?>
            <?php foreach($post as $posts):?>
                <?php if ($i == $j): ?>
                    <li>
                        <div class="timeline-badge"><i class="glyphicon glyphicon-check"></i></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading" onclick="window.location='<?= $this->url('blog',['action'=>'view','id'=> $posts->getId()]);?>'">
                                <h4 class="timeline-title"><?= $this->escapeHtml($posts->getTitle());?></h4>
                                <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> <?= $this->escapeHtml($posts->getDateCreated());?></small></p>
                            </div>
                            <div class="timeline-body" >
                                <p>
                                    <?php
                                    $explodeString = explode('.',$posts->getContent());
                                    print_r( html_entity_decode($explodeString[0]).'.');
                                    ?>
                                </p>
                            </div>
                            <div class="footer-article " onclick="window.location='<?= $this->url('blog',['action'=>'view','id'=> $posts->getId()]);?>'">
                                <p class="button-footer">MORE<i class="fa fa-long-arrow-right" aria-hidden="true"></i></p>
                            </div>
                        </div>
                    </li>
                    <?php $j++;?>
                <?php else: ?>

                    <li class="timeline-inverted">
                        <div class="timeline-badge warning"><i class="glyphicon glyphicon-credit-card"></i></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading" onclick="window.location='<?= $this->url('blog',['action'=>'view','id'=> $posts->getId()]);?>'">
                                <h4 class="timeline-title"><?= $this->escapeHtml($posts->getTitle());?></h4>
                                <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> <?= $this->escapeHtml($posts->getDateCreated());?></small></p>
                            </div>
                            <div class="timeline-body" >
                                <p>
                                    <?php
                                    $explodeString = explode('.',$posts->getContent());
                                    print_r( html_entity_decode($explodeString[0]).'.');
                                    ?>
                                </p>
                            </div>
                            <div class="footer-article " onclick="window.location='<?= $this->url('blog',['action'=>'view','id'=> $posts->getId()]);?>'">
                                <p class="button-footer">MORE<i class="fa fa-long-arrow-right" aria-hidden="true"></i></p>
                            </div>
                        </div>
                    </li>
                    <?php $i++;?>
                <?php endif;?>


            <?php endforeach;?>
        </ul>
    </div>

</div>