<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="/#about">About</a></li>
                    <li><a href="/#skills">Skills</a></li>
                    <li><a  style="color:white; background-image: -webkit-linear-gradient(top,#080808 0,#0f0f0f 100%);" href="<?= $this->url('blog')?>">Blog</a></li>
                    <?php if($this->identity()== true):?>
                        <li class="pull-right"><a href="/admin">Admin</a></li>
                        <?php print_r($this->identity());?>
                    <?php endif;?>
                </ul>
            </div>
        </div>

    </div>
</nav>

<div class="container" id="effect">
    <?php foreach($post as $posts):?>
        <div class="panel col-xs-12 col-sm-12 col-md-4">
            <div class="panel-heading" onclick="window.location='<?= $this->url('blog',['action'=>'view','id'=> $posts->getId()]);?>'">
                <h3>
                    <p class="article-title"><?= $this->escapeHtml($posts->getTitle());?></p>
                </h3>
            </div>
            <div class="panel-body">
                <p class="article-content">
                    <?php $explodeString = explode('.',$posts->getContent());
                        print_r(html_entity_decode($explodeString[0]).'.');
                    ?>
                </p>
            </div>
            <div class="footer-article" onclick="window.location='<?= $this->url('blog',['action'=>'view','id'=> $posts->getId()]);?>'">
                <p class="button-footer">MORE<i class="fa fa-long-arrow-right" aria-hidden="true"></i></p>
            </div>
        </div>
    <?php endforeach;?>
</div>
