<!-- Main jumbotron for a primary marketing message or call to action -->
<!--<div class="jumbotron">-->
<!--    <div class="container">-->
<!--        <h1>Blog</h1>-->
<!--    </div>-->
<!--</div>-->
<div class="container">
    <div class="jumbotron jumbotron-pic">
            <h1 class="text-center" style="color: #fff">Blog</h1>
        <div class="cleaner"></div>
    </div>


<div class="row equal">
    <?php foreach($post as $posts):?>

        <div class="col-xs-12 col-md-3">
            <div class="panel">
                <div class="panel-heading" onclick="window.location='<?= $this->url('blog',['action'=>'view','id'=> $posts->getId()]);?>'">
                    <h3>
                        <p class="article-title"><?= $this->escapeHtml($posts->getTitle());?></p>
                    </h3>
                </div>

                <div class="panel-body">
                    <p class="article-content">
                        <?php
                        $explodeString = explode('.',$posts->getContent());
                        print_r( html_entity_decode($explodeString[0]).'.');
                        ?>
                    </p>
                </div>

                <div class="footer-article " onclick="window.location='<?= $this->url('blog',['action'=>'view','id'=> $posts->getId()]);?>'">
                    <p class="button-footer">MORE<i class="fa fa-long-arrow-right" aria-hidden="true"></i></p>
                </div>
            </div>
        </div>
    <?php endforeach;?>
</div>
</div>