<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Pawel Klaus</a>
        </div>
        <div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <ul class="nav navbar-nav">
                        <li><a href="../#about">Home</a></li>
                    </ul>
                    <li><a href="<?= $this->url('blog')?>">Blog</a></li>
                    <?php if($this->identity()== true):?>

                        <li><a href="<?= $this->url('admin')?>">Admin Panel</a></li>
                        <?php print_r($this->identity());?>

                    <?php endif;?>
                </ul>
            </div>
        </div>
    </div>
</nav>
<div class="container">
    <h1 class="text-center jumbotron">
        <?= $this->escapeHtml($view->getTitle()); ?>
    </h1>
    
    <p>
        <?= $this->escapeHtml($view->getContent()); ?>
    </p>
</div>