<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1><?= $this->escapeHtml($view->getTitle());?></h1>
    </div>
</div>
<div class="container">
    <span class="col-xs-12 date-author"><?= $this->escapeHtml(substr($view->getDateCreated(),0,-8));?> / Pawel Klaus</span>
    <div class="col-xs-2">
<!--        <a class="fb-xfbml-parse-ignore" title="Share this on facebook" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fmyberlincampus.de%2Fblog&amp;src=sdkpreparse"><span class="fa fa-facebook-official fa-3x"></span></a>-->
    </div>
    <div class="col-xs-10">
        <p class="post-content"><?= html_entity_decode($view->getContent());?></p>
    </div>
</div>