<?php

$form = $this->form;

$form->get('title')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Title'
]);


$form->get('content')->setAttributes([
    'class' => 'form-control',
    'rows' => 6,
    'placeholder'=>'Type your content here'
]);

$form->get('submit-post')->setAttributes(['class'=>'btn btn-primary']);
?>
<div class="container"
    <div class="row">
        <div class="col-xs-12">
            <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('content')); ?>
            <?= $this->formElement($form->get('content')); ?>
            <?= $this->formElementErrors($form->get('content')); ?>
        </div>

            <?= $this->formElement($form->get('submit-post')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<script>
    tinymce.init({
        selector:'textarea'
    });
</script>