<?php

$form = $this->form;

$form->get('title')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Title'
]);


$form->get('content')->setAttributes([
    'class' => 'form-control',
    'rows' => 6,
    'placeholder'=>'Type your content here'
]);

$form->get('submit-post')->setAttributes(['class'=>'btn btn-primary','href'=>'..']);
?>

<div class="container">
    <div class="col-xs-12">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('content')); ?>
            <?= $this->formElement($form->get('content')); ?>
            <?= $this->formElementErrors($form->get('content')); ?>
        </div>

        <?= $this->formElement($form->get('submit-post')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<script>
    tinymce.init({
        selector: "textarea",
        height: 500,
        plugins: [
            "advlist autolink autosave link image lists charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
            "table contextmenu directionality emoticons template textcolor paste textcolor colorpicker textpattern"
        ],

        toolbar1: "image fullpage | bold italic underline strikethrough | mybutton | alignleft aligncenter alignright alignjustify | styleselect formatselect fontselect fontsizeselect",
//        toolbar2: "cut copy paste | searchreplace | bullist numlist | outdent indent blockquote | undo redo | link unlink anchor image media code | insertdatetime preview | forecolor backcolor",
//        toolbar3: "table | hr removeformat | subscript superscript | charmap emoticons | print fullscreen | ltr rtl | visualchars visualblocks nonbreaking template pagebreak restoredraft",
        content_css: [
            '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
            '//www.tinymce.com/css/codepen.min.css'],
        setup: function(ed) {
            ed.addButton('mybutton', {
                    title: 'My button',
                    label: 'My Button',
                    onclick: function () {
                        ed.selection.setContent("<img class='img-responsive'>test pic</img>");
                    }
                });
        },
        menubar: true,
        toolbar_items_size: 'small'
    });
</script>