<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1>ADMIN</h1>
    </div>
</div>

<p>
    <a class="btn btn-default" href="
    <?= $this->url('admin', ['action'=>'add']); ?>">
        New Post
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>Post Title</th>
        <th>Date Created</th>
        <th>Actions</th>
    </tr>

    <?php foreach ($posts as $post): ?>

        <tr>
            <td><?= $this->escapeHtml($post->getId()); ?></td>
            <td>
                <a href="<?= $this->url('blog', ['action'=>'view', 'id'=>$post->getId()]); ?>">
                    <?= $this->escapeHtml($post->getTitle()); ?>
                </a>
            </td>
            <td><?= $this->escapeHtml($post->getDateCreated()); ?></td>

            <td>
                <a class="btn btn-info" href="<?= $this->url('admin',['action'=>'edit', 'id'=>$post->getId()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                </a>
                <a class="btn btn-danger" href="<?= $this->url('admin',['action'=>'delete', 'id'=>$post->getId()]); ?>">
                    <span class="glyphicon glyphicon-remove"></span> Delete
                </a>
            </td>
        </tr>

    <?php endforeach; ?>

</table>





