<?php
    $this->headTitle('Create a account');
    //$this->mainMenu()->setActiveItemId('users');
   /*
     $this->pageBreadcrumbs()->setItems([
        'Home'=>$this->url('home'),
        'Manage Users'=>$this->url('users'),
        'Add User'=>$this->url('users', ['action'=>'add'])
    ]);
   */
    $form->get('email')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'name@example.com'
    ]);
    $form->get('full_name')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Max Mustermann'
    ]);
    $form->get('country')->setAttributes([
        'class'=>'form-control'
    ]);
    $form->get('password')->setAttributes([
        'class'=>'form-control'
    ]);
    $form->get('confirm_password')->setAttributes([
        'class'=>'form-control'
    ]);
    $form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
    $form->prepare();
?>

<h1>Start to earn</h1>

<p>
By creating an account you will start to earn today
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

            <div class="form-group">
                <?= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>
                <?= $this->formElementErrors($form->get('email')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('full_name')); ?>
                <?= $this->formElement($form->get('full_name')); ?>
                <?= $this->formElementErrors($form->get('full_name')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('password')); ?>
                <?= $this->formElement($form->get('password')); ?>
                <?= $this->formElementErrors($form->get('password')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('confirm_password')); ?>
                <?= $this->formElement($form->get('confirm_password')); ?>
                <?= $this->formElementErrors($form->get('confirm_password')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('country')); ?>
                <?= $this->formElement($form->get('country')); ?>
                <?= $this->formElementErrors($form->get('country')); ?>
            </div>

            <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>