<!--<div class="jumbotron jumbotron-pic row">-->
<!--    <h1 class="text-center" style="color: #fff">Open Source Work</h1>-->
<!--    <div class="cleaner"></div>-->
<!--</div>-->
<!--<div class="container">-->
<!--    <div class="row flex-row">-->
<!--        --><?php //foreach($myRepos as $repos):?>
<!--            <div class='col-xs-12 col-sm-4 flex-col'>-->
<!--                <div class="panel panel-default">-->
<!--                    <div class="page-header">-->
<!--                        <h3 class="text-center" ><a href="--><?php// $repos->html_url ?><!--" target="_blank" style="color: #E52F26">--><?php// $repos->name?><!--</a></h3>-->
<!--                        <span style="margin-left: 20px;">--><?php// ($repos->language != '' ? $repos->language : 'other' )?><!--</span>-->
<!--                        <span class="text-center"><i class="far fa-clock"></i> --><?php// date( 'M.Y',strtotime($repos->created_at))?><!--</span>-->
<!--                        <span class="text-right"><i class="fas fa-code-branch"></i> --><?php //$repos->forks_count ?><!--</span>-->
<!--                    </div>-->
<!--                    <div class="page-body">-->
<!--                        <h4 class="text-center">--><?php // $repos->description?><!--</h4>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!---->
<!---->
<!--        --><?php //endforeach;?>
<!--    </div>-->
<!--</div>-->
<!---->
<!--<br>-->
<!--<br>-->
<!--<br>-->
<!--<br>-->
<!---->
<!---->
<!--<!-- Global site tag (gtag.js) - Google Analytics -->-->
<!--<script async src="https://www.googletagmanager.com/gtag/js?id=UA-130475199-1"></script>-->
<!--<script>-->
<!--    window.dataLayer = window.dataLayer || [];-->
<!--    function gtag(){dataLayer.push(arguments);}-->
<!--    gtag('js', new Date());-->
<!---->
<!--    gtag('config', 'UA-130475199-1');-->
<!--</script>-->