
<!-- Main jumbotron for a primary marketing message or call to action -->

<!--<div class="row">-->
<!--    <div class="col-xs-12">-->
<!--        <span class="date-author">Pawel Klaus / Projects</span>-->
<!--    </div>-->
<!--</div>-->
<!--<div class="row">-->
<!--    <div class="table-responsive test">-->
<!--        <table class="table">-->
<!--            <thead>-->
<!--                <tr>-->
<!--                    <th> <div class="col-xs-2"><a href="https://github.com/klausberlin/Restaurant-Application" ><img src="/../../img/rest.jpg" width="200" height="200" class="rounded mx-auto d-block" alt="Restaurant Project"></a>Restaurant/Order Project</div></th>-->
<!--                    <th> <div class="col-xs-2"> <img src="/../../img/placehold.gif" class="rounded mx-auto d-block" alt="...">coming soon</div></th>-->
<!--                    <th> <div class="col-xs-2"> <img src="/../../img/placehold.gif" class="rounded mx-auto d-block" alt="...">coming soon</div></th>-->
<!--                    <th> <div class="col-xs-2"> <img src="/../../img/placehold.gif" class="rounded mx-auto d-block" alt="...">coming soon</div></th>-->
<!--                    <th> <div class="col-xs-2"> <img src="/../../img/placehold.gif" class="rounded mx-auto d-block" alt="...">coming soon</div></th>-->
<!--                    <th> <div class="col-xs-2"> <img src="/../../img/placehold.gif" class="rounded mx-auto d-block" alt="...">coming soon</div></th>-->
<!--                </tr>-->
<!--            </thead>-->
<!--        </table>-->
<!--    </div>-->
<!--</div>-->

<!--<div class="placeholder"></div>-->




<div class="jumbotron-pic flex-container row" itemscope itemtype="http://schema.org/WPHeader">

    <div class="col-xs-12 col-sm-12">
        <h1 class="text-center">Pawels Blog</h1>
        <h4 class="text-center">Building web applications</h4>
    </div>
<!--        <div class="col-xs-12 col-sm-12">-->
<!--            <h2 class=" banner-text">-->
<!--               Here you get to know my currently working progress and also what is going on in my life, enjoy.-->
<!--            </h2>-->
<!--        </div>-->


</div>

<div class="cleaner"></div>


<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <img class="img-rounded" title="Pawel Klaus" src="/../../img/placehold.gif" alt="Image">
        </div>
        <div class="col-sm-9">
            <h2>Pawel Klaus</h2>
            <p class="card-text">
                Passionated Application Developer with a focus on web applications
            </p>
            <a class="btn btn-primary" type="button" href="mailto:pawelklaus@hotmail.de">Contact me</a>
        </div>
    </div>


    <div class="cleaner"></div>

    <div class="row">
        <div class="col-md-4">
            <h2>About Me</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-default" href="/about" role="button">Read more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>What I can do for you</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Contact me</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-default" href="#" role="button">Contact &raquo;</a></p>
        </div>
    </div>
</div>


<script>
    $(function() {

    });


</script>