<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container" >
        <div class="navbar-header" >
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="#about">About</a></li>
                    <li><a href="#skills">Skills</a></li>
                    <li><a href="<?= $this->url('blog')?>">Blog</a></li>
                    <?php if($this->identity()== true):?>
                        <li class="pull-right"><a href="/admin">Admin</a></li>
                        <?php print_r($this->identity());?>

                    <?php endif;?>
                </ul>
            </div>
        </div>
    </div>
</nav>

<div id="about" class="container-fluid zigzag" style="margin-top: -10px; background-color: #AFAFAF">
    <div class="container">
        <h1 class="name">
            Pawel Klaus
        </h1>
        <h5 class="status">
          Junior Web Developer
        </h5>
    </div>

    <div class="anim--btn" id="sendemail">
        <span class="anim--btn">
            Contact Me
        </span>
        <span class="btn-email" data-clipboard-target=".email">
            <span class="email" data-toggle="tooltip" title="Click to contact me">pawelklaus@hotmail.de</span>
        </span>
    </div>
</div>

<div id="skills">
    <div class="container">
        <h2 class="about text-center">Skills</h2>
        <canvas id="personal-skills-pie" width="770" height="385" style=""></canvas>
    </div>
</div>
<script>
    $(document).ready(function(){

        new Chart(document.getElementById("personal-skills-pie"),
                {
                "type":"pie",
                "data":
                    {
                        "labels":[
                            "PHP","HTML","Javascript","CSS"
                        ],
                        "datasets":[
                            {
                                "label":"skills",
                                "data":[
                                   70,60,50,60
                                ],
                                "backgroundColor":[
                                    "rgb(149, 111, 221)","rgb(198, 85, 83)","rgb(255, 205, 86)","rgb(42, 72, 198)"
                                ]
                            }
                        ]
                    },
                    options: {
                        legend: {
                            display: true,
                            labels: {
                                fontColor: 'rgb(255, 255, 255)'
                            }
                        }
                    }
                }
            );

        $('#sendemail').click(function (event) {
            window.location.href = "mailto:pawelklaus@hotmail.de.com?subject=I want to know more about you&body= ";

        });

        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
        new Clipboard('.btn-email');

        // Add scrollspy to <body>
        $('body').scrollspy({target: ".navbar", offset: 50});

        // Add smooth scrolling on all links inside the navbar
        $("#myNavbar a").on('click', function(event) {
            // Make sure this.hash has a value before overriding default behavior
            if (this.hash !== "") {
                // Prevent default anchor click behavior
                event.preventDefault();

                // Store hash
                var hash = this.hash;

                // Using jQuery's animate() method to add smooth page scroll
                // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
                $('html, body').animate({
                    scrollTop: $(hash).offset().top
                }, 800, function(){

                    // Add hash (#) to URL when done scrolling (default click behavior)
                    window.location.hash = hash;
                });
            }  // End if
        });

    });




</script>
